---
- name: Install PostgreSQL server package
  become: yes
  package:
    name: postgresql
    state: present
  
- name: Ensure postgres python packages are present
  become: yes
  package:
    name: [ "python-psycopg2" ]

# postgres requires commands (like db creation) to be executed as local user 'postgres' per default
# -> we are not able to use this procedure, because of the 'become unpriv user problem' in ansible
# switching the auth-method from peer is no option either
# -> our procedure: set postgres-pw for db configuration and remove afterwards
- name: Set postgres password
  become: yes
  shell: 'su postgres -c "psql --command=\"ALTER USER postgres WITH PASSWORD ''{{ postgres_tmp_password }}'';\""'
  no_log: true

- name: Create a new database
  become: yes
  postgresql_db:
    login_password: '{{ postgres_tmp_password }}'
    login_host: localhost
    name: sonar
    encoding: 'utf8'
    state: present

- name: Create database user
  become: yes
  postgresql_user:
    login_password: '{{ postgres_tmp_password }}'
    login_host: localhost
    db: sonar
    name: '{{ sonar_db_user }}'
    password: '{{ sonar_db_pass }}'
    priv: 'ALL'

- name: remove postgres password
  become: yes
  shell: 'su postgres -c "psql --command=\"ALTER USER postgres WITH PASSWORD null;\""'
