---
- hosts: all
  become: yes
  pre_tasks:
    - name: Install package dependencies.
      package:
        name: ["unzip"]
  roles:
    - role: geerlingguy.java
    - role: postgres
      when: not sonar_db_embedded
    - role: lrk.sonarqube
